-- Diese Datei wird nur beim ERSTEN Erstellen des Daten-Volumes ausgeführt.
-- Eigene Tabellen, Views oder Testdaten können hier eingefügt werden.
--
-- Beispiel:
-- USE app_db;
--
-- CREATE TABLE example (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100) NOT NULL
-- );
