services:
  mariadb:
    image: mariadb:11.8.8
    container_name: mariadb-server
    restart: unless-stopped

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    env_file:
      - .env

    ports:
      - "${MARIADB_PORT:-3306}:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - database_network

volumes:
  mariadb_data:
    name: mariadb_data

networks:
  database_network:
    name: database_network
